# Cloud Build Configuration for Vertex AI Workbench Fleet Upgrade/Rollback
#
# This configuration supports:
# - Upgrade and rollback operations via _OPERATION substitution
# - Dry-run mode (default: true for safety)
# - Structured JSON logging
# - Parallel execution control
# - Dedicated service account for least-privilege access
#
# Usage:
#   gcloud builds submit --config=cloudbuild.yaml \
#     --substitutions=_PROJECT_ID=my-project,_LOCATIONS="europe-west2-a",_OPERATION=upgrade,_DRY_RUN=true
#
# See docs/cloud-build.md for detailed documentation.

timeout: 7200s  # 2 hours max build time

options:
  logging: CLOUD_LOGGING_ONLY

# Use dedicated service account for least-privilege access
# Create via: terraform -chdir=terraform/cloudbuild-iam apply
serviceAccount: 'projects/${PROJECT_ID}/serviceAccounts/wbi-cloudbuild@${PROJECT_ID}.iam.gserviceaccount.com'

substitutions:
  # Required
  _PROJECT_ID: ''
  _LOCATIONS: ''
  
  # Operation type: 'upgrade' or 'rollback'
  _OPERATION: 'upgrade'
  
  # Safety: dry-run defaults to true
  _DRY_RUN: 'true'
  
  # Optional: specific instance
  _INSTANCE_ID: ''
  
  # Operational parameters
  _MAX_PARALLEL: '10'
  _TIMEOUT: '7200'
  _POLL_INTERVAL: '20'
  _HEALTH_CHECK_TIMEOUT: '600'
  _STAGGER_DELAY: '3.0'
  
  # Upgrade-specific
  _ROLLBACK_ON_FAILURE: 'false'
  
  # Logging
  _JSON_LOGGING: 'true'
  _VERBOSE: 'false'
  

steps:
  # Step 1: Validate required substitutions (Pinned image)
  - id: 'validate-inputs'
    name: 'gcr.io/cloud-builders/gcloud@sha256:fca111b5c9f7f7e580d75e42e29bd4603a1e9785182cddff617fa8c746184473'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -euo pipefail
        
        echo '{"severity":"INFO","message":"Validating build inputs","timestamp":"'"$(date -Iseconds)"'"}'
        
        if [[ -z "${_PROJECT_ID}" ]]; then
          echo '{"severity":"ERROR","message":"_PROJECT_ID is required","timestamp":"'"$(date -Iseconds)"'"}'
          exit 1
        fi
        
        if [[ -z "${_LOCATIONS}" ]]; then
          echo '{"severity":"ERROR","message":"_LOCATIONS is required","timestamp":"'"$(date -Iseconds)"'"}'
          exit 1
        fi
        
        if [[ "${_OPERATION}" != "upgrade" && "${_OPERATION}" != "rollback" ]]; then
          echo '{"severity":"ERROR","message":"_OPERATION must be upgrade or rollback","timestamp":"'"$(date -Iseconds)"'"}'
          exit 1
        fi
        
        # Enforce execution in europe-west2
        if [[ "${LOCATION}" != "europe-west2" ]]; then
          echo '{"severity":"ERROR","message":"Build must run in europe-west2 region. Current location: ${LOCATION}","timestamp":"'"$(date -Iseconds)"'"}'
          exit 1
        fi
        
        echo '{"severity":"INFO","message":"Validation passed","operation":"${_OPERATION}","project":"${_PROJECT_ID}","locations":"${_LOCATIONS}","dry_run":"${_DRY_RUN}","timestamp":"'"$(date -Iseconds)"'"}'

  # Step 2: Build Custom Image (Pre-baked environment)
  - id: 'build-image'
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/${_PROJECT_ID}/wbi-fleet-upgrader:latest', '.']

  # Step 3: Run the operation using Custom Image
  - id: 'run-operation'
    name: 'gcr.io/${_PROJECT_ID}/wbi-fleet-upgrader:latest'
    entrypoint: 'bash'
    env:
      - 'GCP_PROJECT_ID=${_PROJECT_ID}'
      - 'LOCATIONS=${_LOCATIONS}'
      - 'INSTANCE_ID=${_INSTANCE_ID}'
      - 'DRY_RUN=${_DRY_RUN}'
      - 'MAX_PARALLEL=${_MAX_PARALLEL}'
      - 'TIMEOUT=${_TIMEOUT}'
      - 'POLL_INTERVAL=${_POLL_INTERVAL}'
      - 'HEALTH_CHECK_TIMEOUT=${_HEALTH_CHECK_TIMEOUT}'
      - 'STAGGER_DELAY=${_STAGGER_DELAY}'
      - 'ROLLBACK_ON_FAILURE=${_ROLLBACK_ON_FAILURE}'
      - 'JSON_LOGGING=${_JSON_LOGGING}'
      - 'VERBOSE=${_VERBOSE}'
    args:
      - '-c'
      - |
        set -euo pipefail
        
        timestamp() { date -Iseconds; }
        
        log_json() {
          local severity="$$1"
          local message="$$2"
          echo "{\"severity\":\"$$severity\",\"message\":\"$$message\",\"timestamp\":\"$$(timestamp)\"}"
        }
        
        log_json "INFO" "Starting ${_OPERATION} operation"
        log_json "INFO" "Project: ${_PROJECT_ID}, Locations: ${_LOCATIONS}, Dry-run: ${_DRY_RUN}"
        
        # Build Python arguments
        PYTHON_ARGS=(
          "--project" "${_PROJECT_ID}"
          "--locations" ${_LOCATIONS}
          "--max-parallel" "${_MAX_PARALLEL}"
          "--timeout" "${_TIMEOUT}"
          "--poll-interval" "${_POLL_INTERVAL}"
          "--health-check-timeout" "${_HEALTH_CHECK_TIMEOUT}"
          "--stagger-delay" "${_STAGGER_DELAY}"
        )
        
        # Add optional instance ID
        if [[ -n "${_INSTANCE_ID}" ]]; then
          PYTHON_ARGS+=("--instance" "${_INSTANCE_ID}")
        fi
        
        # Add dry-run flag
        if [[ "${_DRY_RUN}" == "true" ]]; then
          PYTHON_ARGS+=("--dry-run")
        fi
        
        # Add operation-specific flags
        if [[ "${_OPERATION}" == "rollback" ]]; then
          PYTHON_ARGS+=("--rollback")
        elif [[ "${_ROLLBACK_ON_FAILURE}" == "true" ]]; then
          PYTHON_ARGS+=("--rollback-on-failure")
        fi
        
        # Add verbose flag
        if [[ "${_VERBOSE}" == "true" ]]; then
          PYTHON_ARGS+=("--verbose")
        fi
        
        log_json "INFO" "Executing: python3 main.py $${PYTHON_ARGS[*]}"
        
        # Execute the operation
        if python3 main.py "$${PYTHON_ARGS[@]}"; then
          log_json "INFO" "${_OPERATION} operation completed successfully"
        else
          EXIT_CODE=$?
          log_json "ERROR" "${_OPERATION} operation failed with exit code: $$EXIT_CODE"
          exit $$EXIT_CODE
        fi

  # Step 4: Upload reports to Cloud Storage (Pinned image)
  - id: 'upload-reports'
    name: 'gcr.io/cloud-builders/gsutil@sha256:f0b63c86624f789909d3c9f2a910efd5187d096a9b55afa307c640158f71b938'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -euo pipefail
        
        # Only upload if reports exist
        REPORT_PATTERN="${_OPERATION}-report-*.json"
        LOG_FILE="workbench-${_OPERATION}.log"
        TARGET_BUCKET="gs://${_PROJECT_ID}-cloudbuild-artifacts/wbi-fleet-upgrade/${BUILD_ID}/"
        
        if ls $$REPORT_PATTERN 1> /dev/null 2>&1; then
          echo '{"severity":"INFO","message":"Found report files to archive","timestamp":"'"$(date -Iseconds)"'"}'
          
          # Upload to GCS
          gsutil cp $$REPORT_PATTERN $$TARGET_BUCKET || true
          gsutil cp $$LOG_FILE $$TARGET_BUCKET || true
          
          echo '{"severity":"INFO","message":"Reports uploaded to '"$$TARGET_BUCKET"'","timestamp":"'"$(date -Iseconds)"'"}'
        else
          echo '{"severity":"INFO","message":"No report files found to archive","timestamp":"'"$(date -Iseconds)"'"}'
        fi
